name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main, site ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: flamed/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install deps
        working-directory: flamed
        run: npm ci

      - name: Build & Export
        env:
          NEXT_PUBLIC_GH_PAGES_REPO: Vef-2-Verkefni2
          NODE_ENV: production
        working-directory: flamed
        run: |
          npm run build
          [ -d out ] && touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: flamed/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
